- id: shfmt
  name: shfmt
  description: Shell source code formatter (native install)
  language: golang
  additional_dependencies: [mvdan.cc/sh/v3/cmd/shfmt@v3.5.0]
  entry: shfmt
  args: [-w, -s]
  types: [shell]
  stages: [commit, merge-commit, push, manual]

- id: shfmt-docker
  name: shfmt
  description: Shell source code formatter (Docker image)
  language: docker_image
  # latest: https://github.com/mvdan/sh/issues/860#issuecomment-1124710547
  entry: --net none mvdan/shfmt:latest@sha256:a89cee7bbb1ded7543169af3aeff1eba97884177f2c9af766105ecf56792bd61
  args: [-w, -s]
  types: [shell]
  stages: [commit, merge-commit, push, manual]
