name: Main push and PR checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # No caching as we're expected to run rarely
      - name: Install dependencies and run checks
        run: |
          python3 -m pip install pre-commit
          pre-commit try-repo . --color always --all-files
